columnSuffix: sdojvdtp
contentColumnType: text
fieldGroup: c866deda-e6cc-48ea-8562-52f0654d5db2 # _Common
handle: ueberschrift
instructions: null
name: Ãœberschrift
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
