defaultPlacement: end
enableVersioning: true
handle: bghwOrganisation
name: '[BGHW] Organisation'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Prim√§re eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a2821711-f9c3-46b0-ae5e-158625c1ee52: # BGHW
    enabledByDefault: true
    hasUrls: true
    template: landingpage.twig
    uriFormat: organisation
type: single
